name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - intesar
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this issue?
      options:
        - Blocker
        - Non-Blocker
    validations:
      required: true     
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ### How we handle bugs: 
        - Duplicate, wont-fix, invalid tagged bugs are closed automatically.
        - Fixed and released bugs are closed automatically.
        - Fixed bugs go live as part of our weekend releases.
        - Blockers bugs go live as part of nightly releases.
        - To escalate an issue, please reach us at our support email handle.
