blank_issues_enabled: false
contact_links:
  - name: Apisec Release Notes
    url: https://apisec-inc.github.io/releases
    about: Please look for release updates here.
  - name: Apisec Security Bugs
    url: https://apisec-inc.github.io/security-bugs
    about: Please report security vulnerabilities here.
